const repos=[
['AI Daily News','AI INFORMATION SYSTEM','每天自动聚合 GitHub Trending、Hacker News 与 arXiv，并生成中文 AI 前沿摘要。','3 stars · 1 fork · GitHub Pages','HTML · Gemini · GitHub Actions','HTML','https://github.com/jiangnan030-del/ai-daily-news','https://jiangnan030-del.github.io/ai-daily-news/'],
['AI arXiv Daily','RESEARCH AUTOMATION','自动追踪 LLM、Agent、RAG、RLHF、多模态与代码生成方向的 arXiv 新论文。','持续日更 · Apache-2.0','Python · arXiv · LLM 摘要','Python','https://github.com/jiangnan030-del/ai-arxiv-daily'],
['PFC Codex Skills','AGENT SKILLS','面向 ITASCA PFC 建模、标定、后处理、声发射和能量分析的可复用 Agent 技能集。','3 stars · MIT','Python · DEM · PFC · Agent Skills','Python','https://github.com/jiangnan030-del/pfc-codex-skills'],
['Symbolic KAN','SCIENTIFIC ML','对 Symbolic-KAN 的可复现 Python 重构，用于方程发现与科学机器学习研究。','1 star · 7 topics · MIT','PyTorch · KAN · Symbolic Regression','Python','https://github.com/jiangnan030-del/symbolic-kan-reproducible'],
['Neural EnKF','DATA ASSIMILATION','Neural Ensemble Kalman Filter 的复现项目，探索神经网络与集合数据同化的结合。','MIT · 公开复现实验','Python · Neural Networks · EnKF','Python','https://github.com/jiangnan030-del/neural-enkf-reproduction'],
['VCD²','CRACK DYNAMICS','从视频中发现裂纹动力学规律，把 ImageJ、MATLAB 与稀疏动力系统识别连接起来。','公开科研项目','ImageJ · MATLAB · PySINDy','Research','https://github.com/jiangnan030-del/VCD2'],
['XHS Card Skill','CONTENT DESIGN','用于小红书信息卡片排版的可复用技能，把内容结构转译为稳定的视觉输出。','1 star · 公开仓库','HTML · Layout · Agent Skill','HTML','https://github.com/jiangnan030-del/xhs-card-skill'],
['Dual-target Calibration','MODEL CALIBRATION','面向颗粒与黏结数值模型的双目标微观参数标定方法。','1 star · 公开仓库','Python · Optimization · Calibration','Python','https://github.com/jiangnan030-del/dual-target-calibration-skill'],
['Paper Daily','KNOWLEDGE PIPELINE','自动生成每日文献日报，覆盖 AI 论文精读、断裂力学前沿与 Notion 归档。','1 fork · 公开仓库','Python · Notion · Publishing','Python','https://github.com/jiangnan030-del/paper-daily']];
const work=document.querySelector('#work');work.innerHTML=`<div class="section-heading"><div><p class="eyebrow">OPEN SOURCE / GITHUB</p><h2>开源项目</h2></div><p>从 AI 信息自动化到科学机器学习与工程计算，这些项目记录了我把研究问题做成可复用工具的过程。</p></div><div class="evidence-switch" role="tablist" aria-label="项目证据视图"><button role="tab" aria-selected="true" data-view="story">简介</button><button role="tab" aria-selected="false" data-view="data">数据</button><button role="tab" aria-selected="false" data-view="tech">技术</button></div><div class="repo-grid">${repos.map((r,i)=>`<article class="repo-card ${i===0?'featured':''}"><div class="repo-top"><span>${String(i+1).padStart(2,'0')}</span><span class="language"><i class="lang-${r[5].toLowerCase()}"></i>${r[5]}</span></div><div><p class="repo-kicker">${r[1]}</p><h3>${r[0]}</h3><p class="view-copy" data-story="${r[2]}" data-data="${r[3]}" data-tech="${r[4]}"></p></div><div class="repo-actions">${r[7]?`<a href="${r[7]}" target="_blank" rel="noreferrer">Live ↗</a>`:''}<a href="${r[6]}" target="_blank" rel="noreferrer">Code ↗</a></div></article>`).join('')}</div><div class="all-repos"><a class="button ghost" href="https://github.com/jiangnan030-del?tab=repositories" target="_blank" rel="noreferrer">查看全部 GitHub 仓库 ↗</a></div>`;
const style=document.createElement('style');style.textContent=`.repo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.repo-card{min-height:350px;border:1px solid var(--line);border-radius:var(--radius);padding:24px;background:#f9f8f5;display:flex;flex-direction:column;justify-content:space-between;transition:.25s}.repo-card:hover{transform:translateY(-5px);border-color:var(--ink)}.repo-card.featured{background:var(--ink);color:var(--paper);grid-column:span 2}.repo-card.featured .view-copy,.repo-card.featured .repo-kicker,.repo-card.featured .repo-top{color:rgba(255,255,255,.66)}.repo-top{display:flex;justify-content:space-between;margin-bottom:58px;font:10px monospace;color:var(--muted)}.language{display:flex;align-items:center;gap:7px}.language i{width:8px;height:8px;border-radius:50%;display:inline-block}.lang-python{background:#3572a5}.lang-html{background:#e34c26}.lang-research{background:#8b8d87}.repo-kicker{font:10px monospace;letter-spacing:.08em;color:var(--muted);margin-bottom:10px}.repo-card h3{font-size:27px;line-height:1.15;margin-bottom:14px}.repo-card .view-copy{color:var(--muted);min-height:84px}.repo-actions{display:flex;gap:20px;padding-top:24px;border-top:1px solid var(--line)}.repo-actions a{font-size:13px;text-underline-offset:4px}.all-repos{display:flex;justify-content:center;margin-top:30px}body.explore .repo-card{background:#202020}body.explore .repo-card.featured{background:#fff;color:#191919}@media(max-width:850px){.repo-grid{grid-template-columns:1fr 1fr}.repo-card.featured{grid-column:span 2}}@media(max-width:620px){.repo-grid{grid-template-columns:1fr}.repo-card.featured{grid-column:span 1}.repo-card{min-height:330px}.repo-top{margin-bottom:42px}}`;document.head.appendChild(style);
const body=document.body,modeButton=document.querySelector('.mode-toggle'),modeLabel=document.querySelector('.mode-label');modeButton.addEventListener('click',()=>{const active=body.classList.toggle('explore');modeButton.setAttribute('aria-pressed',String(active));modeLabel.textContent=active?'快速模式':'探索模式';localStorage.setItem('atlas-mode',active?'explore':'fast')});if(localStorage.getItem('atlas-mode')==='explore'){body.classList.add('explore');modeButton.setAttribute('aria-pressed','true');modeLabel.textContent='快速模式'}
const copies=[...document.querySelectorAll('.view-copy')];function setView(view){copies.forEach(el=>el.textContent=el.dataset[view]);document.querySelectorAll('[role=tab]').forEach(btn=>btn.setAttribute('aria-selected',String(btn.dataset.view===view)))}setView('story');document.querySelector('.evidence-switch').addEventListener('click',e=>{if(e.target.matches('button'))setView(e.target.dataset.view)});
const dialog=document.querySelector('.ask-dialog');document.querySelectorAll('.ask-open').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});const answers={'你擅长什么？':'我关注 AI 自动化、科学机器学习与工程计算，并把研究方法沉淀为可复用工具。','最近在做什么？':'最近在推进 AI 信息系统、科研 Agent 技能与个人开源项目。','如何与你合作？':'请发送项目背景、核心问题与期望时间至 jiangnan030@gmail.com。'};document.querySelector('.quick-asks').addEventListener('click',e=>{if(e.target.matches('button'))document.querySelector('.answer').textContent=answers[e.target.textContent]});
const canvas=document.querySelector('#atlasCanvas'),ctx=canvas.getContext('2d');let px=.5,py=.5;function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const dark=body.classList.contains('explore');ctx.strokeStyle=dark?'rgba(255,255,255,.2)':'rgba(23,24,22,.17)';ctx.fillStyle=dark?'rgba(142,185,255,.7)':'rgba(36,93,245,.55)';const center={x:w*.5+(px-.5)*30,y:h*.5+(py-.5)*30};[[.27,.2],[.79,.31],[.72,.78],[.18,.7],[.14,.46]].forEach((p,i)=>{const x=w*p[0]+(px-.5)*(i-2)*9,y=h*p[1]+(py-.5)*(2-i)*8;ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}draw();const atlas=document.querySelector('.atlas');atlas.addEventListener('pointermove',e=>{const r=atlas.getBoundingClientRect();px=(e.clientX-r.left)/r.width;py=(e.clientY-r.top)/r.height});atlas.addEventListener('pointerleave',()=>{px=.5;py=.5});
